const text = `Now, we begin.
And, indeed, greetings unto you, beloved and holy friends. If I speak in the language of your world, I cannot find those words that can convey to you the Love which I feel for you. I cannot find the words that can convey unto you the Love I feel, that God has for all of us. If I search the languages of your world, I cannot find a concept, a word, an idea, a philosophy, a dogma that can contain, in Truth, the Mystery that is closer to you than your own breath and awaits your discovery.
If I search throughout all of creation, if I search through the many mansions that exist within the domains of my Father’s Creation — and that Creation is infinite — try as I might, I cannot discover anything that can truly describe you. I cannot find that which is of greater value than you. In Truth, I cannot discover anything that speaks more eloquently of the Love that God is, than your very existence. Therefore, in Truth, I look upon you constantly, and marvel at the Radiance of my Father’s Love.
It is, then, through you that I come to discover all that God is. And as a man, when I walked upon your plane, I began to realize that the greatest gift that I could ever receive would only come to me as I chose to surrender every perception that I might conjure up about you, my brother or sister, that would veil the Truth that is true about you always.
When I was of nine years of age, I began to awaken to exactly what I am describing to you. And as my father would take me to sit with the elders, and as he would read from the Torah to me, I began to be compelled by something within. Something began to speak to me, that underneath all of the perceptions that I could create of another, there was something Radiant and Shimmering waiting to be discovered. I began to feel very different from my peers. I began to be preoccupied with inner things. And when I listened to the elders speak, I would often feel as though I had drifted far away from where they were. And pictures would come to me, and thoughts would come to me, and feelings would come to me that I didn’t understand, that I hadn’t assimilated into my being.
But something began to compel me. How might I discover how to see only that Shimmering Radiance? Would it be possible for me to see my brothers and sisters as my Father sees His Children? And, in Truth, I discovered that the way to see with the Eyes of Christ begins with the acceptance that I, as a creator, created in the image of God, indeed, literally choose every experience, and call it to me; that I create the veils through which I view Creation.
And I began to shift gears slightly. I began, even, to be seen as someone who was rebelling against the teachings of my Essene elders. For I began to move away from striving for God, from striving for perfection, and began to cultivate within myself the process of allowing. I discovered that if I looked upon my perceptions, my feelings, my behavior, exactly as they were, without overshadowing them with my own interpretations — if I could teach myself to embrace things with innocence — veils began to be dissolved from my mind. For when I was nine years old, I had already learned to be fearful of thinking, or speaking, or acting, in a way that was not in conformity to the prevailing wisdom of that time, even within the Essene community, which had already become rather rigidified. There was already much dogma. And dogma always leads to bickering.
I began to discover that if I looked with innocence upon all things, a Light began to shine through the things I was looking at. And as I rested more and more in this innocence, more and more, the Light would shine.
And as I grew in age, I began to discover that the old teachers who spoke of the need to, “Forgive seventy times seven,” knew something quite profound that had even become lost within the tradition, the Jewish and Essene traditions, of my day. For, you see, to forgive means “to choose to release another from the perceptions that you’ve been projecting upon them.” It is, therefore, an act of forgiving one’s self of one’s projections. And as we begin to forgive, even unto seventy times seven times, each time you forgive you take yourself deeper into the purity of your own consciousness. You begin to see how profoundly you have been coloring, and therefore affecting, all of your relationships, through the simple act of not being aware of the power of projection.
Therefore, I learned — and learned well — that forgiveness is an essential key to healing. The opposite of forgiveness is judgment, and judgment always creates separation and guilt. Judgment will evoke a sense of guilt in the one who has been judged, unless, of course, they are perfectly awake. But more than this, each time that you judge anything or anyone, you have literally elicited guilt within yourself, because there is a place within you, yet still, that knows the perfect purity of your brother and sister, and sees quite clearly that all things within the human realm are either the extension of Love, or a cry for help and healing.
Therefore, beloved friend, when you judge, you have moved out of alignment with what is true. You have decreed that the innocent are not innocent. And if you would judge another as being without innocence, you have already declared that this is true about you. Therefore, to practice forgiveness actually cultivates the quality of consciousness in which, finally, you come to forgive yourself. And it is, indeed, the forgiven who remember their God.
And so, therefore, in this hour, beloved friends, we would wish to share with you the power of forgiveness — how to cultivate it, how to refine it, how to understand the depths of it that can be revealed to you as you forgive seventy-times-seven times, how to bring up within you that which has not yet been forgiven, but perhaps forgotten. We would speak also, in this hour, of what perception is, and what projection is.
Beloved friends, these things are of critical importance. For anyone who enters into a so-called “spiritual path” must eventually face and deal with their deep need for forgiveness, which is an expression of the soul’s deep desire to be forgiven. For there is no one who walks this plane who has not been touched by the poison of judgment.
Beloved friends, as we speak of these things, though, let not seriousness enter the mind. For in Truth, all we are really doing is describing for you what you need to do, and can do, in order to release the burden of illusion that seems to cause you to feel a heaviness upon your countenance, a sense of a lack of safety in the world. You could think of it as taking your rheostat and turning it up a bit by enlightening you, taking your burden of guilt and judgment from you.
Therefore, in Truth, understand well: forgiveness is essential. And what has not been forgiven others, has not been forgiven you — not by a God that sits outside of you, for the Father never judges. What you have not forgiven in another or in the world is but a reflection of what you carry within as a burden that you cannot forgive of yourself.
You have an interesting saying in your world,
It takes one to know one.
Do you think you would even be able to judge another if there wasn’t something within you being elicited that triggers within you the belief that you know exactly what that other one is up to? And that’s why you judge them. And sometimes, you judge harshly because you fear that energy in yourself, or you remember how hurtful you have been when you have acted from that energy.
But when you have forgiven yourself, rest assured, you will know what it means to walk in this world yet be not of this world. You will be able to feel the energy or the activities that any other soul may freely choose. And you will discern that energy, you will understand that energy, you will see through it, and still see the Face of Christ before you. You will not react, which literally means “to act again, as you did in the past.” Instead, even if you are being persecuted (or to speak from personal experience, to be nailed upon a cross), you will have cultivated the ability to love.
And in all situations, no matter what another is doing, your first response will be to enter into the quiet stillness within, and merely ask the Holy Spirit,
What would you have me say? What is most appropriate for this other soul in this moment?
For when forgiveness has purified the mind and the heart and the emotional field of your own beingness, you will discover that you exist only to extend Love.
You are the Savior of the world. And in each situation, your role is to ask the Holy Spirit how you can serve the Atonement, the correction, the healing, that yet needs to be acquired within another soul. So even if one is hating you, you will not respond with defensiveness but with curiosity, with innocent witnessing. And even if your hands have nails going through them, I tell you truthfully, it is possible to still enter the quiet sanctuary of the Heart and to ask of the Holy Spirit,
What would you have me say or do that can serve the healing of my brother or sister’s heart?
So, that is where we’re going. And all that we will be sharing with you, not just in this hour, but in this year, has as its final goal your complete Christed Consciousness, the fulfillment of what your own soul desires: forgiveness.
There is, first, nothing you can be aware of in the energy of another that you have not known in yourself. There is nothing another can say or do, or even imagine themselves capable of saying or doing, that you have not also known. Again, it takes one to know one. And when you perceive another acting out of hostility, or fear, or what have you, the only way you can recognize it is because you have been there.
The very fact that, in your world, one can murder another’s body, and you can react with a knowledge that that is inappropriate behavior, is because, as a soul, you know the energies involved in the attempt to murder another. And, in Truth, if you’re honest with yourselves, you can probably come up with at least fifty times in the last year that murderous thoughts have entered your mind. You may not act on them, you may not even dwell on them for more than a split second, but the energy has come into the field of your awareness, and you have known it and recognized it. Who, then, is less than you? Who, then, is worthy of your judgment? No one. Who, then, is equal to you? Everyone. And who, then, is worthy of your love? Everyone.
Forgiveness is the bridge that links you to the soul, the essence of your brother or sister. Forgiveness is that bridge, that when cultivated, will allow you to see clearly not just the energies that another is expressing, but you will literally be able to see what events seemed to cultivate that soul’s belief that they must act in that way to survive, to live — what perceptions have led them to feel justified in their inappropriate behaviors. You will see it as clearly as though someone had drawn a picture in front of you. And then you will see skillfully what to say, and what to do to gently help another correct their misperceptions of themselves and learn the path of self-forgiveness. And when that hour comes, rest assured, you will walk in this world, yet you will not be in it. You will be as I became. You will be the Savior of the world.
What is projection? Projection occurs when there has first been denial within yourself. Projection is an act in which you psychically try to throw out of your ownership everything that you have judged as being despicable or unworthy of you, something you don’t want. And so you will project it. You will throw it up and out, and let it land on whomever happens to be near by. Projection is the effect of the denial of the first axiom that we have given you. It is the denial of the Truth that nothing you experience has been caused by anything outside of you. Projection then, is the attempt to insist that reality is other than the way God made it. That you are not powerful, that you are a victim of circumstances, that you’re in a world that can actually do things to you and make you - cause you to make - decisions that you wouldn’t have made otherwise. That is always denial. And it is a lie.
Projection is the denial of the first axiom of Truth. And you’ve mastered it well. When you project onto another, you will then believe that your anger, your hatred is justified. Rest assured, there are many in your legal system … in fact, the legal system means merely to take the act of projection and the need to judge and to make it okay socially, so that you need not be concerned with this other as your brother or as your sister, who has been crying out for help. But rather you become justified in punishment. And yet, punishment, itself, is only the insane attempt to convince the punisher that the darkness, the evil — whatever you want to call it — is not in them, it’s out there.
Imagine, then, a society in which the prevalent legal view is simply that your brother or your sister is an aspect of yourself. And if you would help yourself, you must help them — to meet each cry for help and healing with forgiveness, love, and support. Can you imagine, for a moment, what it would be like to live in such a society? How would it be different than the world you see?
And yet, if you would have these things be different, it must begin with you. For the way to heal the world is not by seeking to change what is on the outside, but by first changing what is on the inside. For when that change has occurred, you will become a conduit for an energy that knows how to use your gifts, to place you in just the right situations. And a great Power will work effectively through you — the Power, alone, Which knows how to heal your world. There are many, indeed, that would love to march for peace by angrily attacking those who make war. But if you would create peace in the world, you must be at peace within yourself.
So, projection is an act of trying to get rid of what you don’t want to own within. It is the effect of the denial of Truth. Projection colors your brother or sister with the very energies that you would judge within yourself. How, then, to begin to break the pattern of projection? How, then, to allow the bridge of forgiveness to be built? It is actually quite simple, but it will require your commitment.
I have said to you many times, that the world you see is nothing more than the effect of the thoughts you have held within the mind. Therefore, awakening requires the act of vigilance and discipline — the discipline to cultivate a way of living in which you observe your own thoughts, in which you listen to the words that are coming out of your mouth, in which you observe the feelings that are evoked within your body, the reactivity that seems to own you, and to see these things as innocent and simply self-caused.
When next, then, something is reflected to you by the world that causes you to become angry, causes you to be in judgment, stop right where you are, and look, not with judgment of your judgment, but with innocence and honesty:
Oh, I see that I am judging someone. That’s an interesting cloud passing through the sky of my awareness. I wonder if I might be able to make another choice?
Now, the mind will tell you,
But this person just broke into my house and stole my stereo. Of course I have a right to be in judgment! I have a right to feel angry.
But I say unto you, anger is never justified. It doesn’t mean you won’t experience it, but stop fooling yourself into believing that there is some validity to it. What if that one who has just broken into your home and taken your stereo equipment, or what-have-you (some other idol that you love …. hmm), what if you understood that you had the power in that moment to remember that all events are neutral? They merely provide you with a chance to choose Love.
What if you literally chose the “insane” way, according to the world, of looking upon that one, who has just done that act, as a brother or sister who is crying out for help and healing, who does not know how to live in this world without being of the world, who does not know the way to self-forgiveness, that does not know the Truth of the Light that lives within them, that does not recognize their great power to create whatever they want in a way that is not hurtful to anyone — to look upon them with compassion rather than reactivity?
It begins in simple ways. And to set the stage, I want you to very much remember that time has been given to you that you might use it constructively. That means when you awaken in the morning, realize that you are in school. You don’t have to drive anywhere, you’re already there. And that the universe is literally helping to assist you into having experiences that will bring things up for you, so that you can choose to look at them differently – thereby, discovering the great power within you, the freedom within you, to choose what you want to perceive, to elicit only what you want to feel. So again, that even if nails are being driven through the hands, you finally are liberated in the power to choose Love, and, therefore, to overcome this world.
Having said this, understand then, that each of your days is a blessing and a gift, if you use it from the full commitment to awakening. Your day is chock full of a million opportunities to discover a deeper Truth. Therefore, never feel that the purpose of your life must be something other than what you’re involved in. For remember what we spoke of earlier: You are literally creating everything you choose, and nothing is forced upon you.
And now we’re going to take that thought just a little deeper for a moment, because it literally means that if you have decided you want to awaken, it means you have already called to yourself every experience that can truly best serve your awakening. And the friends and the family, the people you have relationships with, are those who likewise can best gain from the experiences elicited through your relationships. It means that right here, and right now, you’re already demonstrating the power that you’re seeking — the power to truly choose to awaken, and to command the whole of Creation to serve you in that awakening.
Therefore, when you awaken in each of your mornings, look around. Who’s that person sleeping next to you? They are your perfect companion. They are a messenger of God. And just behind all of that, you see, because your mind is resting right next to the Mind of God, when you first said it as a soul, “I want to awaken, I want to go home,” the Father answered your prayer and began to send the thought through your spirit and through your soul to your conscious mind,
I know how to direct you home. Give up this career and start that one. Move from this location to that location.
And you began to feel all manner of impulses. You began to read different books. You began to do different things. You met someone and fell in love. All by accident? Hardly!
So, the very thought that you would claim as your own, from which you have created the world of your own personal experience, is also, literally, the result of your prayer to awaken. And the Father is creating — assisting you to create — just those experiences as stepping stones that carry you from where you are to where God is. The result is that your ordinary daily life is the most perfect ashram you could ever be within. It is the Holy City to which it is wise to make pilgrimage every day, which means to bring awareness and commitment to exactly what you are experiencing, to be thankful for it, to bless it, to embrace it, to be vigilant, to be mindful:
What is this moment teaching me?
In your ordinary moments, a thousand times each day, you’ll be confronted by opportunities to be disturbed. [laughs] Hmm! And in that very same moment, you are being given the blessing of the opportunity to choose peace, to remember to cultivate a perception of your brother or sister that is a perception birthed out of the Christ Mind, not the egoic mind. Forgiveness, then, can be practiced diligently. And you won’t need to look too far. You will not need to make a pilgrimage to some far city. You do not need to go sit in a cave in the mountains somewhere to discover the way to God. It is all around you, because you can only be where you have decreed to be. And you have decreed to be there because you, as a soul, truly want nothing more than to awaken. And your life, your life just as it is unfolding, moment to moment, is meant for you.
If this is true, and I assure you that it is, the way to God can only be found in your willingness to embrace and live fully the very life that is within you, that unfolds through you with each moment. To live without fear, to go forward, to indeed, trust, to embrace the very power and the majesty that is the seed, the soil, the ground from which your life’s experience is unfolding. It is precious! It is extraordinary! It is blessed! And it is given you of God! Would you not embrace the blessing of your life, and sanctify it to keep it holy, and to, indeed, draw the line and recognize that your life is worthy of your respect? It doesn’t matter what anybody else thinks. It matters what you think.
Beloved friends, your life — your life — is your way home! If you do not live it fully, how can you ever arrive home? Therefore, fear not your greatness. Fear not the power that comes from embracing your life and claiming its value. Live it full out with every bit of passion you can muster! Embrace every second of it! Every time you wash your dish and your cup after breakfast, look upon these things and go,
My God! This is my life! This is my pathway home! And I am going to live it!
Indeed, precious friends, in this way, you will come to forgive yourself of the judgments you have made. For who among you has not known the feeling of saying,
God, my life just isn’t worth very much. I’ll never be like so-and-so down the street. And I’ll never have enough money. And not enough people are going to know me. And when will my work ever get out as big as that person’s work?
…etcetera, etcetera, etcetera.
But I say unto you, every time you’ve judged yourself, you have weakened yourself. Every time you have judged yourself or another, you have slipped down the mountain another notch, when your desire is to be at the summit.
Understanding these things, then, let us look more closely at forgiveness. How does it work? What really occurs when you forgive? You are a conduit of energy. To the degree that the conduit is in perfect working order, the energy can flow so radiantly that the conduit actually becomes transparent. That is, it no longer blocks. There is no barrier or limit to the Light. When you judge, it is as though you contracted, you made the walls of the conduit smaller, just like building up rust in your pipes. And the flow becomes less and less. As you forgive judgments, it is as though the rust in the pipes were dissolving. It is as though the walls of the pipe, that are carrying the liquid of God’s Love, begin to expand and become thinner and thinner and more transparent. Judgment is contraction. Forgiveness is relaxation, and peace, and trust, and faith.
Forgiveness allows the spaciousness within your consciousness to grow. For when you look upon the thief that has broken into your home and say, “I forgive you,” you are decreeing the opposite of what you’ve learned. You are decreeing that nothing can be taken from you of any value. You are decreeing that judgment is the opposite of what you want, and it will cause you to feel the opposite of how you want to feel. You are decreeing your power to perceive differently. You are, therefore, healing yourself.
And if you ever want to come home, you’re going to have to become very, very divinely selfish. You’re going to have to become so selfish that you will not tolerate judgment in yourself — of anyone or anything. Because you will begin to recognize that every little act catapults you to the other side of the Universe from where you want to be. It causes the very cellular structure (if you could see this, you would never judge again)  . . when you judge, even the cells of your body go crazy. They vibrate in a completely dissonant way. And there is contraction. The fluids do not move through the cells. The nutrients do not become transported or delivered to the cells. The waste matter isn’t processed properly. Everything gets clogged up, and there is dis-ease.
Therefore, beloved friends, understand well that judgment is not something to take lightly. Should you, then, judge yourself if you’ve noticed you’ve been in judgment? No. That’s a judgment in itself. Only Love can heal. Therefore, when you know you’ve judged, go,
Ah, yes! That’s that energy. I recognize that cloud that has just passed through the field of my awareness. But, I can choose again.
So, how does this work? If in your “ordinary” daily life — that we now know is not ordinary at all — if you detect that you have been in judgment of someone or some thing, recognize that that judgment is still with you. It’s a present thing, even though you may have enacted it five minutes ago, or fifty-five years ago, or ten lifetimes ago. When you notice it, or bring awareness to it, you have made it a very present thing. So it’s right there in front of you to be undone. And that’s what you need to focus on:
I’m going to choose again.
Know you the experience of looking back in your life, and suddenly seeing a scene in which now you know you behaved selfishly from ego; that you were manipulative or cunning or hurtful? Or you recognize,
My God, I was really in judgment of that person. Ah! Ooo! If only I could go back and undo it.
Know you that feeling? I say unto you, you can, because everything is present. There is no such thing as past and future, there is only now. So when you have that thought or that memory, it’s coming to you for a very specific reason. As a soul, you are learning about forgiveness and how to undo the effects of your previous choices. And so, it is being presented to you, yet again, that you might make a new choice.
So when that old memory comes, stay with it. Look at it. Recognize how judgment worked at that time. And then say to that person and or that event,
I judge you not. I extend forgiveness to myself for what I have created. I embrace you, and I love you. And I free you to be yourself. And I bless you with the Blessing of Christ.
Then see that image or that memory begin to gently dissolve into Light, until there is no trace of it left. And be done with it.
And right away the mind says,
Well, yes, but when I kicked that little boy in the shins when I was four years old, just to watch him scream . . . he’s not here.
Isn’t he? The body is not here, but the body is not quite the soul. And all minds are joined. It means that where you extend forgiveness within the consciousness, within your emotional field, to another, whether they be physically present or not, you are extending to them exactly what you could extend to them if they were physically in front of you. Because, you see, even if they were, they still have to receive it, don’t they? They still have their choice to make — whether to accept your forgiveness, or to remain in judgment of you. And that’s their issue, not yours.
Understand then, that you are dealing with consciousness. You are not a physical being, you are Spirit. And you are intimately linked with all minds and all times. Therefore, forgiveness of another can occur anytime you decide that it can occur. Anyone you’ve ever believed has wronged you, can be forgiven by you, in this very moment. Anytime you’ve judged another and, therefore, been in judgment of yourself, you can undo that in the very present moment, simply by making a different choice.
Rest assured, you will continue to project upon others what remains unhealed, unforgiven within yourself. Each time you react to another, you are being given a sign that there’s some kind of energy that’s been presented to your awareness that you have not forgiven within yourself. If someone is critical, and that pushes your buttons every time they’re critical, rest assured, you have not healed that part of your own beingness — that part of your own experience of being critical of others. Whether it’s occurring now, or whether it seems to be a pattern that you have interrupted and no longer do, you’ve still not forgiven yourself for having identified with that energy.
Use your ordinary experience, then, in each day to observe what pushes your buttons. And if you will stay with it — and in just a moment we will give you a very simple technique for doing so — if you can stay with it, it will reveal to you the energies that are in need of your forgiveness.
The technique is quite simple. As you go through your day, observe when you feel as though you are in contraction. Are the muscles of the body tight? Is the breath very shallow? Does your voice become faster or louder when you speak about some energy in someone else? That is a sign that you need to do healing within yourself. When you recognize that these kinds of signs are going on — in other words, life has presented you with an opportunity to be disturbed — that is a sign that there is something that requires healing.
So therefore, count it a blessing if you feel disturbed. Turn your awareness from what you think is causing the disturbance and remember the first axiom:
I am the source of my experience. I’m feeling disturbed. What is it in me that needs to be healed?
Begin to breathe deeply with the body and rhythmically. Let the body soften and relax, and ask,
What is it within this person’s energy that is really pushing my button?
And you will see it right away:
Oh, they’re so critical. Criticism pushes my buttons. Where have I been critical of others?
And it might hit you right away:
Well, I’m being critical because they’re critical.
Or memories will come back, distasteful memories, if you’re judging them. Let them come back. Continue to breathe and relax. Look upon that energy of being critical. Honor it. Love it. For it is a creation. It is your creations coming back to you, that you might embrace them and transform them. And in that example, just stay with it. Look at it.
Ah! Being critical. Yes, I can sure be critical. I’ve been that way in the past. I know that energy very well.
Look upon a scene in your memory in which you have been the one being critical. Look upon it with deep honesty and sincerity, and say to yourself,
I forgive me for being critical. I forgive my judgment of myself. I choose to teach only Love.
Watch that image disappear from your mind, dissolve from your mind. And bring it back to the present moment and that person that just pushed your button. Again, you don’t need to say anything to them at all, although you might. But, within yourself, forgive them for allowing the energy of being critical to temporarily make a home in their mind. And merely ask the Holy Spirit to replace your perception with the Truth. Ask to see the innocent Light within them.
As you cultivate this, you’ll become very, very good at it. You’ll be able to do it that fast [snaps his fingers]. And once you begin to see the Light in them, you can ask the Holy Spirit,
What is this critical energy in them masking? What are they really crying out for?
And then you will feel compassion. For it will be revealed to you why they are hurting inside. And, lo and behold, instead of being reactionary with them, you just might be compassionate. Your choice of words, your own behavior might turn out to be different than you could have ever imagined. And yet, through you will be channeled exactly what serves them.
When I was being nailed to the cross, there was, indeed, one who raised the mallet to strike the nail. And as he raised the mallet, his eyes met mine, for just a moment. And I did exactly what I’ve described to you. I first remembered, and by this time I had mastered this, so that it was done very quickly. I asked,
How have I ever wanted to drive a nail through someone else?
And I remembered my murderous thoughts. I forgave myself and brought my attention back to that one, and asked only to see the Light in him. And I asked,
What is it that this action is mirroring to me? What is it masking within him?
And I saw that one’s soul, and I loved that one’s soul. And I felt compassion for that one. And in that moment — mark my words — in that moment of eye contact, that one got it!
Because my energy was different, it created the space in which that soul could make a new choice. And that soul saw suddenly the entirety of its experience, and realized that if it allowed that mallet to fall upon the nail, it would be a decision to choose to continue being nothing more than a doormat for other people’s perceptions. And in that very instant, that soul decided to follow a path that would lead to sovereign mastery, and never again to be a pawn of any government, or any group, or any faction, or anyone. He dropped the mallet from his hand — this was a Roman soldier — stood up, and walked away, and disappeared.
That one has gone on to become a Master that is known by literally thousands of beings. He is not in physical form. This one visits many, teaches many. This one, indeed, incarnated perfect mastery, and therefore, transcended the world. And it all began as the result of my desire to teach only Love. And now, we have a very good friendship.
So you see, you may not know how powerful your choice for healing is. You may not really see how deeply and profoundly it will affect you, as you go on being a creator — and you go on forever. And you could never possibly know what fruits will be born from that tree in the life of another. But because all minds are joined, when you choose healing, through forgiveness, you literally create the space in which the other can also heal their life.
Let no moment, then, be wasted. See nothing as ordinary. And see not the perceptions taught to you of the world be justified within yourself. But be you wholly committed to rooting up and out of your beingness anything that is unlike the Love of Christ. Think not that I am the only one that can love this way — it is not true. You are here to love as I learned to love. Why? Because you are that Love. And everything else is just a smoke screen.
Forgiveness is necessary. Forgiveness is a skill and an art that will pay you dividend upon dividend upon dividend upon dividend. It will never cease in paying you. Each moment in which you choose forgiveness, you have literally saved yourself a thousand years of suffering! Whoo! And I mean that about as literally as one can mean it. In short, every act of forgiveness is a miracle that shortens the need for experience in this dimension. And when you find yourself in a situation that you believe is too big, rest assured it is because something big has finally come to the surface to be healed within you, so that more power can shine forth through you, because you’ve reached the place where you’re ready for it. More of Christ can be lived.
It is very, very important to let each day be sufficient unto itself. That is, when you end your day, always truly end it. And do not take four hours of ritual. You can do it within one breath. As you take a deep breath, as you rest your head upon the pillow, look upon the whole day, embrace it with your consciousness, and as you let your breath go out, say within your consciousness,
I release and forgive this day. It has been perfect. And it is done.
Let it go, just let it go. Why? Because if you don’t, you’ll just bring it with you. Know you that experience? And for three weeks later you’re going,
Oh gosh, why did I make that decision three weeks ago? If I only would have made a different decision, this wouldn’t have happened, that wouldn’t have happened.
That’s probably true. But the point is, now, three weeks later, you’re still hitting yourself over the head by bringing the past with you. And you miss the glory of the present. You’ve all heard that a thousand times, because it’s the Truth.
Consciousness is a very subtle and powerful thing. You cannot help but create. Remember the goal this year is to learn to deliberately create with perfect mastery. Therefore, look upon the things of the day and say,
It is very good. And it is finished.
Let each night, when you rest your head upon the pillow and you know you are about to go off to sleep, be just like God was in the story, your Biblical story of creation, in which it is written that on the seventh day, God rested. God was finished, in a sense, within the story. And have that same quality at the end of each of your days. If you’re carrying some kind of emotional reaction because of something someone said or did, or whatever, or something you said or did, practice forgiveness before you sleep. Because if you don’t, you will keep experiencing the conflicted energies during your dream states. And communication between you and the other one, who has not yet been forgiven, will keep on going on until that forgiveness is complete within you.
I hope that makes sense to you, because it’s very important. Time should never be taken frivolously. Play with it, yes, but play with it out of consciousness, out of clarity, out of recognizing that there is no such thing as an idle thought. Each thought creates a world of experience for you. And you are worthy of experiencing Heaven.
We will have much more to say about forgiveness as we begin to plummet the depths of what is discovered as you practice forgiveness seventy-times-seven times. It takes you deeper and deeper into the very mechanics of consciousness itself — the very mechanics of creation. Forgiveness. Put it at the top of your list until you know how perfectly forgiven you are. Be you, therefore, vigilant against denying what is still in need of forgiveness within you. For what you deny, you will project. And each projection is a hurtful act to yourself. Also to the other, of course, but to yourself.
So! We will let that be enough for Having given that, then, as background and foundation, remember that you do not experience anything that is called an “ordinary moment.” In each and every moment, extraordinary things are occurring. Extraordinary things are occurring in which the whole of the Universe is conspiring — which means to “breathe together” — the Universe is conspiring with you to awaken you, to heal you. Trust it! Love it! That these things are true — and I assure you that they are — it means that your life, the very life you are living, is equal in power and majesty and effectiveness as any life that has ever been lived. It means that your very life is equal to the one that I lived. For it is bringing you home, as my life was my pathway home to God.
And so, to build on what we shared earlier, the third axiom or principle could be encapsulated in this way:
I do not live any ordinary moments. With each breath, my experiences are the stepping stones laid before me of God, to guide me home. Therefore, I will bring awareness to each moment and allow it to teach me how to forgive, how to embrace, how to love and, therefore, how to live fully.
now. There is much that has been said in this hour that needs to be listened to again, and yet again, so that the awareness begins to truly grasp how important, and how powerful forgiveness is. You will reach a place where you absolutely delight in going through your day expressing forgiveness, like a wave emitting itself from the ocean of your consciousness, even if nobody is doing anything. Forgiveness, itself, becomes a delightful energy to live within.
Therefore, indeed, beloved friends, forgive you well yourself, and you have forgiven Christ. And when Christ is forgiven, Christ will arise and make His home in your heart, and in your mind, and even in the cells of your body. And you will know what it means to walk in this world, yet not be of the world. And when you look in the mirror, you will say,
Behold, the Savior appears.
It will not be egoic arrogance that says it, but the recognition of what is true always:
I am my Father’s Child, and I am sent into this world to bring Light to it.
So! Be you, therefore, at peace. Practice forgiveness well, until it becomes like taking a breath. And you will discover power that you didn’t know could exist, and a freedom whose taste is sweet above honey.
I forgive you [laughs]. Not because I’ve judged you, but because I know the blessing that forgiveness brings to me. Forgiveness is something I perfected as a man. Perfect it within yourself, as well, and you will know the Glory of Christ.
Be you, therefore, at peace, beloved friends.
Amen.`


export const getChunk = () => {
    const lines = text.split('\n');
    const randomIndex = Math.floor(Math.random() * lines.length);
    let chunk = lines[randomIndex];
    let tokens = chunk.split(' ').length;

    let earlier = randomIndex;
    let later = randomIndex

    while (tokens < 1600) {
        if (earlier > 0 && (Math.random() > 0.5 || later >= lines.length - 1)) {
            earlier -= 1;
            chunk = lines[earlier] + '\n' + chunk;
            tokens += lines[earlier].split(' ').length;
        } else if (later < lines.length - 1) {
            later += 1;
            chunk = chunk + '\n' + lines[later];
            tokens += lines[later].split(' ').length;
        } else {
            break;
        }
    }

    return chunk;
}