const text = `Now, we begin.
And once again, greetings unto you, beloved and holy friends. Once again, it is with great joy that we come forth to abide with you in this manner. It is with great joy that I come forth with my friends to abide with you in this hour. It is with great joy that I walk with you on the way that you have chosen. For in Truth, there is not a time that I am not with you. There is not a place to which you can journey where you will not discover my presence.
Only reality can be true. And reality is simple: there is but the simplicity of Love. And from that ocean there is birthed a multitude of forms, a multitude of worlds, a multitude of creations, of which you are one. And like waves arising from the sea, those creations remain linked eternally to their Creator. You are a wave arising from the Infinite Ocean of the Love which is the presence of God. I am a wave that has arisen from the ocean of my Father’s Holy Mind. And though two waves seem to appear separated by what is called time — by even two thousand of your years — yet, in Truth, when seen from a much broader perspective, those waves have arisen simultaneously from the Ocean’s surface. They arise for the very same purpose: to express the simplicity, and the innocence, and the beauty, the creativity, the truth, and the reality of the Ocean Itself.
And the waves delight in expressing what seems to be a unique individuality. And yet, they carry the common thread of being made of the same substance and are truly governed by the same Laws of Creation. For they know not the moment of their own arising, for only the Depth of the Ocean unseen can know the moment when It chooses to well up and to create the expression of the wave. The power that is not seen, but is hidden in the Depth of the Ocean, rises up through and forms that wave and sustains that wave throughout the duration of its expression. And it is from the Depth of that Ocean that it is decided when that wave shall return to the sea. Does that mean it disappears? Only from one perspective. But in reality, the very substance that was made manifest truly has not known birth and death, but only expression.
What, then, if you were to consider yourself as a wave arising from the Holy Mind of God, born of God’s infinite desire to expand Himself, to express the infinite nature of Love and creativity? What if you began to realize that all that you have called yourself is the effect of Love — that you do not cause yourself to come into existence? And yet, as you have arisen from that Ocean of Love, is not the wave made of the same substance as the sea itself? Are you not given infinite and perfect freedom? For just as your Father perceives you, you are given the freedom to perceive yourself, and all of the other waves you might notice, and even the Ocean Itself, in any way that you choose.
The goal, then, of a genuine spirituality is to realign the quality of your perception, to mirror, to resonate with, to be in perfect alignment with the perception of your Creator; to see with God’s eyes. Beloved friends, in Truth, you remain as you are created to be. And in each and every moment, you are literally using the power, found in the silent depth of the Ocean of God’s Love, that gave rise to your very creation and existence, to perceive as you desire.
Therefore, in this hour, we will address the very nature of desire itself: what it means, what it signifies, how it creates effects, the power of desire, the value of desire, the meaning and purpose of desire, and how to begin to bring that energy (which at times, you know, feels like a team of a thousand wild horses all wanting to go in their own directions), to bring the very Power of Desire under your conscious and deliberate direction, that you might, indeed, create as the Father created you — with perfect, deliberate, infinite Love, with perfect and infinite and deliberate freedom, with perfect and infinite and deliberate joy, and with perfect, perfect, freedom.
Desire! When I walked upon your planet as a man, I confronted many different opinions about the nature of creation, the nature of mankind, the nature of consciousness, although the word was not around at the time — what you call consciousness or self-identity. Just as you are now confronted with many schools of thought, so, too, was I. And while that can seem to lead to great confusion, as though one must choose from the smorgasbord, it actually serves not unlike the sand inside the oyster from which the pearl will come. It causes you to grate inside. You must find your own way to your own truth. For before each and every one of you lies your pathway and a doorway, an eye of the needle, through which only you can fit.
Therefore, in some respects, you are seemingly alone. You must make the decision to desire, above all things, awakening into perfect remembrance of your union with God — just as a wave might finally decide that it has been birthed, not to be fearful of being a wave, but to truly claim its individuation, to claim its uniqueness, and to live that fully. And in that fullness, to decide to discover a way to be aware of its infinite union with the ocean itself, to somehow break free of the myopic self-identification as one little piece of wave that arises in a place or a field of time, lasts for but a second and then disappears. To find a way to transcend that limitation, to become re-identified with a consciousness, a living awareness, that you are One with the Depth of the Sea. That you can operate, not from the superficial level of awareness that might be like the foam at the tip of the wave (what you call your conscious or egoic mind), but that you become informed in all that you speak, in all that you do, in all that you create, and all that you perceive, by that which rests in the very Infinite Depth of the Ocean Itself.
Imagine, then, drawing upon a well within you that seems to have no bottom and sides, through which something is pouring forth from places unseen, in which your literal conscious attention, your conscious awareness, seems to be colored with Radiant Light that literally leaves you feeling that you are not the body-mind or the personal history with which you had identified before, but that these things are only temporal, or temporary and very impersonal effects of a level of desire, within your soul, which is one and the same thing as the Love of God expressing Itself, for no other reason than that Love must be extended.
Imagine transcending your fear of your own survival, because as you look upon your body-mind you are no longer identified as that body-mind; that those things have become tools to be utilized by the Love which rests in the Mind of God; that you live, yet no longer you, but Christ dwells as you. This is a very real experience to be lived. It is not just a philosophy. It is not just a concept, and it can never be a dogma. There is a mystical translation that occurs in the depth of the soul which, in Truth, is merely a shifting of where you perceive your sense and source of identity. And the energy, the energy required to take you from myopic self-contraction, in which you have become identified with the little drops of foam out on the tip of the wave, tossed to and fro by a power that seems to be outside of you, to a sense of identity with the Silent Depth of the Ocean, that is everywhere present and seems to know no beginning or no end, the very energy that will carry you from the tip of the wave to the Depth of the Ocean, is the energy of desire.
For I say well unto you, that if the Father had not desired to extend Love, you would never have come into existence. Your very sense of awareness of self is the result, the effect, of Love. The very same Love that has birthed the sun and the moon and all of the stars and every dimension upon dimension upon dimension of Creation. That very Love that desired for that Love to be extended is the very Source from which you have been birthed. As you know yourself to be, then, you are the effect of God’s desire to extend Love.
Therefore, when next someone asks you, “Oh, who are you?”, please do not give them a name. Do not say,
Well, I was born in a certain town, in a certain part of the planet.
Don’t tell them that you are a Democrat, or a Republican, or a communist, or an atheist, or a Catholic. Tell them the Truth:
Who am I? I am the extension of Love in form. I have never been born and I will never taste death. I am infinite and eternal. I shine forth as a sunbeam to the sun. I am the effect of God’s Love. And I stand before you to love you.
Now that will raise some eyebrows! It will also transform your world. For it is time to stop seeking Christ outside and start choosing to take responsibility for being Christ incarnate. Desire is everything!
Take just a moment, right now. Let the body relax, and imagine that you could move back from being the actor in the play of your life to being the director and the producer. And you’re sitting in your laboratory, your studio, and you’re editing the story of your life. And you’re looking at all your little clips of film, from the time you were birthed, the time you went to kindergarten, the time you first fell in love, the time you first decided to go to a movie, the time you went off to college, the time you took a job, or this job or that job, or you moved to another physical location. And look closely and see if it is not true, that for every action you have ever done, for every decision you have ever made, after trying to analyze it all, is there not underneath it the energy of desire?
For in Truth, you do not lift the body from your couch to go to the refrigerator without the desire to eat. Something calls you into a field of action, an expression of action. It is desire. No one enters into an intimate relationship without the energy of desire. For who two have ever looked upon one another and said,
I don’t feel any desire whatsoever, but let’s get married, have children, and raise a family.
Desire! Desire is that energy which brings forth all waves of creation out of the depth of the ocean itself. And yet, who among you has not felt conflicted about desire? Who among you has not been taught that desire is evil? Who among you has not been taught not to desire to be great? Who among you has not been taught that the desire for material comfort is some sort of a blot on the spiritual path? Look well within your soul and see if this is not true. Have you not feared, at times, the welling up of desire within you? For well, as I look upon your plane, there are many who become paralyzed with fear just because they desire to have a bowl of ice cream. So afraid are they, that if they give in to that desire, something in the ice cream will cause their body to bloat and their brain to cease functioning. Hmm! Hmm!
And for those of you in intimate relationship — what you call marriage, a commitment of some kind (there seem to be many levels of commitment in your world, each has its own definition) — how many of you have not carried the belief, taught to you by the world, that if you feel an energy of desire welling up within yourself, when you look upon someone who is not your partner, that somehow you have sinned against God? How many of you, then, do not know the experience of trying to reign in the ten thousand horses, so sure that if you gave in to feeling desire, that everything would run amok? And your attempt to keep your life structured and rigid and predictable, would collapse — what you call “all hell breaking loose.” Hmm!
And yet, I say unto you, would you exist if God had feared the desire to create and extend love by forming you, at the same time giving you infinite freedom of choice? Without desire, look around, not only would you see nothing, there would be nothing to do the seeing. Everything is the effect of desire.
Come, then, to see that desire is not evil. It is not to be feared. It is to be mastered. Mastery is not control. For control, the need to control, is an effect of the energy of fear, and not Love. Mastery of desire comes when you recognize that you are safe to feel whatever wave of desire might come up through your consciousness, because you decide whether or not you will act on it — you will bring it into the field of manifestation. The power of choice is the one power that can never be taken from you. You already have perfect mastery of it, because nothing you ever experience comes to you without your decision to allow it into the field of manifestation.
Come, then, to feel that desire is something welling up from the depth beyond yourself that can be looked at with perfect innocence, and with the wonder of a child. And that that very act of turning to allow and welcome desire is not something that will sidetrack you from the path of awakening, but will, indeed, take you vertically, if you will, into the Heart of God.
For if you are to ever create as God creates, you will need to heal your conflicted perceptions about desire. You will need to transcend that energy of fear.
There are many who call unto me and pray. There is not an hour in your time frame in which there are not many upon your plane, somewhere on your planet, that are praying to me, that want their hearts to be filled with Christ. And yet, at the very same time, they are scared to death of an energy that wants to move, because they have been taught to fear, to suppress, desire.
Desire is like the Liquid of Life that moves through the stem of the rose and allows the petals to radiate with glorious color. And when you block the flow of desire, the petals cannot be nourished. Death begins to occur — death of the heart, death of the soul, lifelessness.
If you were to walk down one of your city streets and to truly look into the eyes of everyone you see (and everyone that hears these words has had this experience), would you not recognize that death seems to have already made a home in the minds of many that are living — death of dreams, death of hope, death of worthiness, death of playfulness, death of true power, death of union with their Source and Creator?
Healing requires the willingness to feel desire, to see it as good, to see it as holy. Does that not mean that if you feel a desire, that it might not become twisted by the egoic patterns in your mind? Of course not. There’s always that possibility that desire will be twisted to meet the needs of egoic mind within you. But rest assured, if it does, who’s done it? You! Always within you, you know that desire is good, but you suppressed it. Always, when desire comes forth, those times when you’ve let it become twisted into serving the goals of the ego, rest assured, you knew perfectly well what you were doing, and you were the decision maker.
You have learned, therefore, to fear desire because that fear is the effect of fearing yourself. And that is what cripples you. That is what cuts off the creative flow. That is what leads to everything your world knows as the multitude of psychological diseases — an unwillingness to trust one’s self, an unwillingness to love one’s self, the belief that the desires that move up through your beingness are something evil and dark. If only you could stamp them out of your being, you could remain in control and everybody would like you because you’d conform to the smallness and the littleness that is worshipped in human consciousness.
Listen well, now, to the next axiom we would give you:
The only relationship which holds any value at all is your relationship with God, your creative Source, the depth of the ocean.
And right away the mind wells up,
But what about my mate, what about my parents, what about my children, what about the President of the United States, what about the postmaster?
Hmm! You will come up with a million examples of relationships that surely have great importance. The only one which holds value is your relationship with God. For when that is in alignment, all of your creations, your choices for relationships, and how you will be within them, will flow effortlessly from that alignment. Therefore, seek first the Kingdom, and all these things will be added unto you. Do not try to create a rose by starting with the petals. But nourish the roots, and the flower must blossom.
If you are to be in right relationship with your Creator, it is absolutely necessary to correct your perception and relationship with the energy of desire. And it begins by releasing your judgment of it in all of its forms. For again, you can only be in Love or fear. You can only be in innocence or judgment. Love and innocence are of the Kingdom. Fear and judgment are of illusion.
Learn then, through simple practice, to interrupt the patterns you’ve learned from this illusory world, so that you release judgment of the energy of desire. This will be different for each and every one, depending on where they begin. But to give you a very simple exercise, when you awaken in the morning, and you’ve planted your feet firmly on your floor, take pause and ask yourself this question:
What do I want right now?
Right away, the mind will say,
Well, I’m too busy to know what I want, I have to go off to work. I have to serve everybody else. I’m here to satisfy the world. I have no time to ask myself what I want.
Remember that what you decree is, and the thought you hold in the mind will be reflected through the nature of your experience.
So take pause and ask,
What do I want?
And then simply give yourself one minute to observe whatever comes up in the mind, or even is felt in the body. Heaven forbid, you might want to have sex! Oh! Then you would know for sure that you are not a “spiritual” being! You might want to take a hot shower. You might want a glass of juice or water. You might want to sing. You might want to stretch or breathe. You might want to turn and look at your lover, your mate, still sleeping in the bed. You might want to arise, and go and sneak into your children’s room, and watch them sleep. You might want to sit down and read the morning paper. But the point here is to notice that by asking the question, something will respond within you. And when that response comes, notice that there is a feeling associated with it, a quality that makes your cells sing just a little bit. That is the energy, the elixir of Life, called desire.
In this one minute, you need not rise to act, but to simply observe:
Ah, what do I want? To take a hot shower.
The feeling of the thought, or the thought that emits the feeling in the body, “I want to take a hot shower,” is carried on the elixir of desire. And desire is coming from a depth of your beingness that, again, rests right next to the Face of God. And might it not be the case that by following the desire that wells up through your heart, by feeling it, by embracing it, you might learn and discover what the Ocean is wishing to express through the wave that you are? And if you judge desire, might you not be shutting off the creative flow that the Mind of God wishes to express?
Of course, that’s the problem. You’ve tied the hose in a knot through conflicted judgments. And the idea, now, is to begin — in a simple way — to begin to give yourself permission to feel desire, to allow it even into the cells of the body, to observe it, to notice it, to sit with it.
Here is a very common one in your world (be honest with yourself): How many times have you felt the desire to be wealthy? It’s not something you’re supposed to sit around and talk about or make very public:
Boy, this morning I woke up and I just imagined having so many golden coins that I could buy the entire planet! Oh! “Money is the root of all evil.” I can’t think that way. Well, I better get busy and get off to my office job, that secretly, inside, I really resent , because they don’t pay me what my soul is worth. But I’ll pretend like I’m quite fine. Oh, money? No, I’m quite fine. I really have enough, and no, no, I’m really quite fine.
And then as you drive home, and the Mercedes Benz pulls up along side you, you cannot help but turn and go,
God, I wish I could afford one of those. Oh, God! I can’t have that thought, so I’ll drive my old Volkswagen down the road. But I’m being a very good spiritual person.
Be honest with yourselves: How many times have you felt, welling up within yourself, the desire to be wealthy? What on earth has caused you to fear that desire? What has caused you to tie the hose in a knot, so that you try to block that desire from coming into manifestation? Perhaps, when you were a child, you went to one of your cathedrals. And there was someone in a long robe standing upon a platform. And because everything looked so beautiful, surely they must be speaking with authority. And because this cathedral is filled with a whole lot of small little minds that are all living in their own level of fear, when that voice spoke and said, “Money is the root of all evil,” you said,
Oh. Well, that is the truth. Oh, yes. That’s the truth. Oh, yes. Oh, God! I better fear money.
Hmm!
I say unto you, you have one Authority, and it is never held within the office of any church, or any organization, or any one individual. Your Authority is the Voice for God that dwells within your heart and within your mind! God is not limited, and does not require His Children to be limited. For if you would receive all that God would give you, you would decide to rise up and be the grandest wave that you could possibly be. For only in so doing do you honor your Creator.
So you could say that God is like a wise gardener who is constantly trying to grow beautiful roses. He knows exactly how much moisture to put in the soil. He knows how to make those nutrients rise from the soil through the roots, up through the heart of the stem of the flower to give forth radiant color, so that everyone that looks upon it is touched by the mystery of beauty. And God wonders,
Well, it’s interesting. These roses that I’ve created seem to have a mind of their own. As the elixir I tried to give them rises through the stems, they tie themselves in little knots, and only a little bit of the elixir reaches out, and so the petals never quite blossom fully.
Have you ever had that feeling that you’re putting more energy into staying constricted than you are into allowing expansion?
Desire is creation. Therefore, what you desire is of supreme importance. If you will take the little exercise that we have given you and begin to put it into practice, in a very simple way, and in a quiet way, you’ll begin to get back in touch with the innocence and beauty of the movement of desire. You can delight in it. When you have a sexual thought, a sexual desire, why not just be with it? Why not notice what it causes to happen in the body? How does your breath change? Does the heart beat faster? Be honest with yourself, isn’t it putting a smile on your face? What if you decided to honestly embrace that effect as being perfectly innocent and beautiful? How might your day change if you did not repress awareness of sexual desire? You’ll notice we’re not saying you should walk down the street and grab every body that walks by you. We’re talking about allowing yourself the living embrace of exactly what energy is moving through your being.
Why is this important? If you have decided that there are certain energies which are demonic, evil, have the power to distract you from your union with God, you have already decided there is something beyond the reach of your power. And that is what disempowers you. And so, you take an innocent energy and turn it into a monster that must be feared at all cost.
Yet I say unto you, the mystical transformation that carries you from feeling yourself to be a disempowered little drop of foam on the edge of a wave, to the sense of freedom and empowered living that flows from the Mind of God, through you, to express only beautiful creations filled with majesty and power and miracles — what takes you from A to B is the willingness to turn to the very energies that move through the mind and the body, and to not fear them, but to look upon them with innocence and wonder. And this is the source of the myths that have been told in all cultures: the knight that slays the dragon, kissing the wild beast on the cheek and it becomes a loving, loving companion. Your monsters are what you fear and repress, because of the judgments you have learned in the world. And the world is only the denial of the Kingdom. It is the exact opposite of Truth.
So you see, if you’re sitting in one of your cathedrals and everyone is saying,
Oh, yes. Sexuality, very bad! It will keep you from God.
Right away, you should realize if everyone here is fearing sexuality, it must actually be Divine, and,
Perhaps I would do well to embrace it, and love it, and master it, and not fear it.
If someone says unto you,
Money is the root of all evil,
and then sticks out his hand, and says,
Would you please make a donation to our organization? . . .
is that not an expression of conflict? And yet, such conflict permeates the religions and dogmas of your world:
Don’t desire money. Don’t desire wealth. By the way, to keep on this radio station, we really need you to send a donation.
What are they trying to teach you? What are they in denial of?
Sex and money. Pretty basic things, aren’t they? They represent energies that flow from the Mind of God, that would express in unlimited joy and power, and not be willing to settle for limitation of any kind.
When the earth was birthed from God’s Holy Mind, and took on its own form, and became an entity just like you, God did not say,
Well, this is a pretty beautiful planet, but I can only have a solar system just large enough for the Earth.
Rather, out of joy, God allowed there to come forth solar system upon solar system upon solar system, the birthing of a thousand suns every moment, as a field in which this beautiful jewel of a planet could spin. That is true creation! And what quality of solar system have you decided to allow, in which the planet of your own awareness can spin and live and express?
Ah desire! Desire is everything. And again, the simple exercise we’ve given you will begin to free up the blocks within, and you will rediscover the innocence of desire. And then, you can begin to expand upon it, to take a few moments to learn to live deliberately.
What do I truly want?
For you see, because your mind shines forth like a sunbeam to the sun from the Mind of God, when you use your consciousness to relax into the innocence of the question
“What do I truly want? What is it in my heart that keeps calling to me, keeps compelling me?”
… pictures begin to arise, feelings begin to arise. And I say unto you, they are expressions of — and we’ll speak through the symbols that you understand of your world — they are expressions of what God wants to bring forth through you,
Oh, every time I look in my heart, and every time I allow myself to feel it, what I really want is — I want to put my arms around people. I want to let people know how much I love them.
Why fear such a desire?
It’s too overwhelming. I don’t know how I’ll be accepted.
Who cares how you’ll be accepted? What matters is how you accept yourself.
What if by feeling that desire, new pictures began to come to you? And suddenly you realized, “What I want to do is join the Peace Corps,” as an example. Perhaps it is the case that that very decision to go and put yourself in a solar system where you can spin as your own planet, where you can go and be in the Peace Corps, could be the very pathway through which you learn to receive the great joy of letting your Love out into the world. But if you fear desire, how can you ever know these things?
Oh, when I get in touch with my heart, and when I allow myself to feel …!
What comes up by asking that question?
I want to have so much wealth. Oh! And I see the thought that says, “Oh, no! Wealth is bad.” But what I want to do is, I want to be able to go to every hungry child on the planet and feed them. That’s why I want to be wealthy.
Could it not be that the desire to feed the world is God’s desire to speak through you, to use you in a way that effects transformation upon your planet? Can you see, then, that by blocking the feeling of desire you might just be blocking yourself from hearing what you keep praying for, over and over?
Father, reveal Thy purpose to me.
You feel the desire and you go,
Oops! First … excuse me, Father … I have to get rid of this desire.
Desire in the heart is where you will discover the phone line that links you to the Will of God that would be expressed through you. And if you don’t trust desire, you are literally saying that you have decided not to trust your Creator. Hmm … not something to just be brushed aside.
In healing the conflict around desire, now that you know what it truly is, learn to be patient with yourself.
By way of a second exercise, and we would suggest that you create a structure by which this can be practiced that fits into your own life. Again, it need not take more than five, ten, or fifteen minutes, initially, perhaps three or four times a week. Eventually, you’ll be doing this all the time, because you’ll be creating deliberately. For just ten or fifteen minutes, set aside your world. Remember that you need do nothing, and so the world can wait.
Relax the body and close the eyes. And it can be of great benefit to let the breath become very deep and rhythmic; it relaxes the nervous system and seduces the controller within your mind, the critic that decides what thoughts are okay and which ones aren’t. By the way, the critic is never something you created. It is something you let live in your mind that was made up by a lot of other fearful minds, called parents and teachers.
As you relax the body and the mind, ask yourself,
What do I truly want?
And observe the images that come, without judgment. Notice the feelings in the body, and allow this to go for just a minute or two. Then pause, open the eyes, and write down all that you can remember.
I saw the image of having forty-seven sexual partners.
I saw the image of having golden coins rain down upon me so that I have to have an umbrella over my head.
I saw huge bowls of ice cream.
I saw myself in a boat on the ocean.
Whatever it is, write it down.
I notice that my stomach got tight.
I thought I was going to pee my pants.
Whatever it is, write it down.
Then, take a deep breath, relax again, and repeat the process. Place the hand so that it rests on the heart. Breathe into it a few times, and then ask,
What do I truly desire?
And again, allow the process to be what it is. Do this over a period of ten or fifteen minutes so that you repeat the process at least six or seven times, writing them down.
Take the piece of paper, perhaps in a journal, as you would call it, and put it aside until the next exercise period, and then again repeat the process. When you have done this seven times, so that you have seven sheets of paper in which you’ve gone through this process, then, and only then, begin to look back through all the things that came up. And then ask yourself,
What seems to be repeating itself?
You might notice,
Well, three times I wanted a huge bowl of ice cream, but then it seemed to fade away.
Twice I had a desire for forty-seven lovers, but now I notice that I’m really only wanting one.
Whatever it might be, notice the pattern, the thread, that seems to run the most throughout the exercise periods. Then, imagine that thread to be that energetic link that is tied at one end to the piece of foam at the edge of the wave, and the other is anchored to the Depth of the Ocean. And then consider that perhaps if you allowed yourself to move down that thread, to begin to put your energy on that, to begin to clear up the obstacles within your consciousness that block that desire from being consistently lived from, that by so doing, you would carry yourself from the drop of foam at the edge of the wave to the Heart of God. And that along the way, everything unlike Love would come up for you to release it. And that during the process, you would go through a metamorphosis that would culminate in your being the living incarnation of the Power of Christ — that your soul would realize the fulfillment that it has always sought. Hmm! Something to take a big gulp over.
For you see, the reason you have cleverly decided to trick yourself into blocking the energy of desire is that the soul knows that, were it to follow such a thread, through whole and total commitment, it will be embarking on the pathway we spoke of in an earlier hour, the pathway set before you by God, that knows how to take you home.
And if you arrive at home, it will mean that you will have had to give up being a seeker. And you will have had to become one who is found. And you will have to rise above the crowd. You will have to give up all of your identity with smallness. You will have to give up needing the approval of others. You will have left the nest of insanity. You will have arisen and taken up your right place at the right hand of God. Isn’t that the deepest fear you carry . . . to actually be the Truth of who you are: Christ Incarnate?
Now, desire can be much fun. Ideally, once you’ve practiced this on your own, ask your mate or a close friend (you may even want to show them this talk on your video) — and ask a friend if they would be willing to embark on this process with you, so that, perhaps once a week, you can sit down together, and say,
What did you come up with this week?
Well, here goes… !
It is called undressing in front of a friend. It is called becoming vulnerable with another. It is called finding another child to play with in the Kingdom, so that you can go to the sand box, away from the adult world that says,
Desire is bad. You guys be careful.
And you begin to look at what is true and real from a place of innocence. And you begin to create for yourself a support group. And that support group perhaps can grow to three or four friends — or even ten or twenty — in which everyone is involved with getting in touch with what’s really in there, by understanding the principle that desire is the thread that links your soul to the Heart of God. And God wants only to extend, through you, that which expresses Love in the world. It is called Creation.
Perhaps, a worthwhile project. For when you do not turn to allow the embrace of desire, there is only one alternative. It is to live in mere survival. And when you choose the energy of mere survival, the world is your master, before which you will be made to bow again and again and again and again and again — lifetime after lifetime after lifetime! You will be a slave to the insanity that seems to rule this world. And you will never know peace. And you will never know joy. And you will never come home. Plain and simple! For you were not created to wither and die on the vine. You were made to bear forth much good fruit.
Let the roots be watered by desiring, above all things, to become the fulfillment of what God had in Mind when He breathed into you the Breath of Life. And let that Breath be received in each moment. You will come to see that the only question — the only question — you need be preoccupied with is this:
How much of God am I willing to receive and allow to be expressed through me?
It is called the separating of the wheat from the chaff. The chaff are the thinkings of the world that would have you believe in smallness. This can only result in your perpetual suffering. The wheat is the food that gives Life, because it is filled with the Love of God.
Fear not, then, desire. But desire to embrace desire. Touch it, feel it, know it, dance with it, sing with it, look at it innocently. Feel it wholly. And then learn to discern, through the ways we’ve given you, what desire is truly: that thread that’s shining forth through all of your days. And then decide to let that desire inform your choices, so that you create a life that serves the fulfillment of that thread of desire.
You see, I had to do the same. For I began to notice that there was a thread of desire in my heart to create some form of demonstration that would be so overwhelming that anyone who turned their attention to it could not help but be reminded that there is something far greater to life than living to survive, and surviving just to live. And even when I was young, I began to get glimpses — at first, they were fleeting. Something was compelling me. But as I learned to trust desire, the pictures became clearer and clearer. And I saw myself standing on hilltops, surrounded by multitudes. And I marveled at the words that came through my mouth in these moments of revelation, when I was still but a teenager. I saw glimpses and pictures of being loved by millions. I saw pictures and things that I couldn’t even comprehend, because they were literally pictures of what I’m doing now. And how could a teenager, living in Judea two thousand years ago, have any way of comprehending the use of the technologies of your modern world in which to communicate Love? It made no sense to me. But still, I decided to trust it.
A part of that thread was the recognition that death is unreal. And so, therefore, I ought to be able to create a demonstration that would prove it. Now, think about that for a moment. If that thought was born in you, and you tried to share it with the world, wouldn’t you be told you were crazy to dare to think a thought so out of line with everything the world believes? But because I followed the thread of desire, I began to realize that it kept speaking to me, day after day, and week after week. It wanted to grow. It wanted to be nurtured.
So finally, I decided,
I am going to allow that thread to be nurtured. And I’m going to discover where it takes me, and what it’s all about.
And where it took me was into mastery of life and death, mastery of healing, mastery of consciousness. It took me into mastery of myself. It brought me home to my own Christed Beingness.
Because I followed that thread, I can talk with you today. There are many of you that appreciate what I have done, because you see me as a spokesperson for the Truth. Is it not time that you followed your own thread, and became, likewise, a spokesperson for reality? For just as you have been sent to me, there will be many sent to you, as you step from being a seeker to a finder. For as you take up your right place, you become a vehicle through which the Voice for God will creatively touch the lives of countless persons that you may never ever meet physically.
You were birthed to be grand. You were birthed for greatness. You were birthed to shine forth such Light into this world that the world remembers that Light is true, and darkness is illusion. Be you, therefore, that which you are. And you are the Light of the world. And I will delight in journeying with you. For if I can join with this, my beloved brother, to create communication, so too, can I join with anyone who chooses to step into their own Christedness. And the thread is the thread of desire.
Therefore, begin to turn toward the energy of desire within yourself — to separate the wheat from the chaff — by first learning to feel it, for just a minute, without judging it, and then to deepen that process. And I tell you, you will reach the point where, with every breath you breathe, you are in touch with the energy of desire. And that is the only Voice that you will give authority to.
And you won’t be able to keep up with the loving creation that wants to express through you. And you will marvel at the friends that come into your life — how your external solar system, in which your planet is spinning, changes. You will marvel and wonder how it’s all happening. And you will finally discover that you are not the maker and doer of your life, that God wants to direct and make Life through you.
And then you will know the Truth that sets you free:
Of myself, I do nothing. But my Father, through me, does all things. And it is very good.
Be you, therefore, at peace. And desire well. For when you feel desire, you are watering your roots with the energy of Life itself. Trust it! Embrace it! And let the petals of the rose blossom within your Holy Being.
We love you, and we are with you. If you could only see how much enlightened help there is surrounding you at any moment, you would never allow the fear of going astray with your desire to be victorious within your mind. And you would step forth with boldness. And all things would be made new again.
How much of God’s Love are you willing to receive?
And with that, we close by saying,
Amen.`

export default text;