const text = `Now, we begin.
Beloved friends–greetings unto you. We come forth in this hour to continue that pathway which builds the structure, the highway, if you will, by which you may learn to follow and, therefore, master The Way of the Heart.
A way in life means to have chosen, from all possibilities, that one which will stand out as the way to which you are committed, the way to which you devote the whole of your attention by granting your willingness that the way be followed. And just as when you take a journey upon your Earth, by making the commitment to take the journey, you avail yourselves of experiences that could not come to you in any other way.
When you go to a university to pursue a pathway of a degree, although you begin with a certain idea of what the pathway may hold or bring you, is it not true that the relationships which come along the way, the knowledge that reveals itself to you, and even the end result of the accomplishing of the degree, always seems to be different than, and much richer than, you could have imagined when you began your journey?
Therefore, understand well that The Way of the Heart requires the willingness to commit. And commitment is nothing more than a deliberate decision that something will be so. And just as with all aspects of experience you’ve ever known, when all of your beingness is involved in the willingness to make a decision, there is literally nothing that can prevent you from the accomplishment of your goal. Rest assured, then, that whenever you believe you have not succeeded or not completed some decision, fueled by desire, it is because you were simply not wholly committed — or it means that you decided to change your mind. And when you change your mind, you literally change what you experience in the world, or the solar system in which your self spins.
The Way of the Heart, then, does indeed require the decision of commitment. And rest assured, I say unto you, that when you wholly commit to discovering The Way of the Heart, you will discover a way of being in the world that is not here. You will discover a way of walking through life in which you experience being uplifted by something that seems to be forever beyond you, yet is within you as the core and the essence of your very beingness. Your way will not be understandable by the world. Your way will not even be comprehensible within yourself. You will be living from mystery — moving from mystery to mystery to mystery — uplifted and carried by something that brings a satisfaction and a fulfillment to the depth of your soul, far beyond anything you can now imagine.
Is it worth it, then, to commit to The Way of the Heart? Yes! The Way of the Heart culminates with the recognition that you do not live Life at all but, rather, that Life is living you. One of its characteristics is the development of the witness — a quality of consciousness, a way of being, in which you seem to be witnessing everything that arises and flows through you and around you, from a place of utter stillness.
Stillness does not mean non-activity. It does mean non-attachment to activity — whether it be the arising and falling away of cancer in the body, the arising and falling away of relationship, the rising and falling away of a solar system. You will discover that there is a place within you that can look upon all things with perfect equanimity, perfect acceptance, and perfect Love. For in mastery of The Way of the Heart, you will discover that nothing is unacceptable to you. And only what is accepted can be transcended. You will discover a way of being in which nothing any longer compels you — not even the desire to know God compels you any longer, for the need of it has been completed.
Then, there arises a way of being in the world that is indeed not here, for you will feel no restlessness, no need to direct your journey. No questions will arise. You will be at peace. And in that peace, the Breath of God will move through you. And you will become as the wind, knowing not where you came from or to where you are going, but you will abide in perfect trust and perfect rest. And the world may not know you, but your Father will know you — and you will know your God.
In The Way of the Heart, the most primary and fundamental perception which seems to fuel ordinary human consciousness has been finally transcended. The perception of a separate maker and doer has been dissolved, and once again you will understand the depth and the profundity of the simple terms in this sentence:
Of myself, I do nothing. But, through me, the Father does all things.
To rest in such a perception means that you have come to realize that the self that you are is merely a conduit through which Mystery lives Itself, through which Love pours forth. You will realize that there is nothing to be gained or lost in this world. You will know what it means to recognize that you literally have nowhere to go and nothing to achieve. You will become empty and spacious.
And yet, paradoxically, while the body lasts, you will appear to be as everyone else. You will arise in the morning and brush your teeth. When the body is hungry, you will feed it. You will laugh with your friends. You will yawn when the body is a bit tired. And yet, through it all, there will be a quality of awareness — called the witness — that is simply watching it all, waiting to be moved by the wind of Spirit. And though others may not see it, virtually everything you utter will carry the sound of Truth.
You know not how Spirit will work through you, nor will you care. Because, you see, when there is no maker or doer or director, it won’t matter to you. That is what it means to live as the wind, for the wind does not concern itself with where it’s been or where it’s going. It is moved by some mysterious source that cannot be located at all. And yet it blows, and as it blows its effects are experienced.
Imagine then, a life in which all that you do is not for yourself. Imagine a way of life in which what you do is not for anyone else. Imagine a way of life in which creativity, living, flows forth from a Source so deep within you and around you that no language or dogma can contain it — a Force and a Source that knows how to express Itself through you in such a way that it is constantly and only serving the Atonement, the awakening of all of Creation to the Truth of God’s presence.
The Way of the Heart, then, does indeed unfold, if you will, along a certain pathway. And in this hour, we will address the stages of that pathway, in a general sense. And then we will speak of the most important characteristic to be cultivated along this path.
First, desire is everything, and without it not a thing can arise. Therefore, indeed, what you desire is of utmost importance. Desire, then, perfect union with God. Desire, then, to be Christ Incarnate. Desire, then, to be all that your Creator has created you to be, even if you haven’t an idea what that might be. For when you hold desire within your beingness, and when you’ve moved through the process of coming to master the energy of desire (and, again, mastery does not mean control), when you have mastered the energy of desire by grounding it always in the desire to be as you are created to be, then indeed, all of your life and all of the subsequent, or subsidiary, desires will come to serve that grand desire.
When you come into that state of being, nothing shall be impossible unto you. And why? Because you’re not the one doing it. You are merely a piece of thread in a very cosmic tapestry, being woven by the Creator of all of Creation, Who alone knows how to weave the tapestry of a new age, of a new paradigm, of a healing of this plane and of humanity. And so the first stage is, indeed, the stage of desire. And only by feeling desire, and not by suppressing it, can you truly begin to move toward the stage of mastery in which the energy of desire always serves that Higher Will, which is the Will of God for you. And as we have said to you before, when your will is in alignment with the Will of God, you will discover that God’s Will for you is that you be genuinely happy, through and through — content, fulfilled, at peace, empowered, capable, responsible.
Desire, in time, is cultivated through intention. For you see, you have used time to teach yourself how to be distracted by all of the thoughts and perceptions that make up this cosmic soup called your world. And all of you have known the frustration of having a desire, and then as soon as you walk out the door a friend pulls up and says,
Let’s go to the beach.
And you never make it to class, even though your desire is to get the degree. You have cultivated the art of being seduced by distraction. Therefore, it is necessary to utilize time to cultivate intention. For without intention, desire cannot become the crystal clear focus, the laser-like focus, that can cut through the dross of this world, that a new creation can flow forth through you.
Intention is not the same as holding a strong egoic, willed, commitment to making something happen. For The Way of the Heart recognizes that you have not known how to achieve the fulfillment you seek at the level of the soul, for the simple reason that if you did, you would have already accomplished it. In The Way of the Heart, intention doesn’t mean putting your nose to the grindstone and not taking “no” for an answer. It means, rather, that you cultivate within your thought processes the art of remembering what you are truly here for. You are here to remember that you are the thought of Love in form. You are here to remember that you are One with God. You are here to remember that what I have called Abba, the Father, though it goes by many names, is the source of your only reality. And you are living in reality only to the degree that That One is living through you.
Therefore, intention in The Way of the Heart means to utilize time each day to focus your attention on the desire to be Christ Incarnate. Intention is that energy, or that use of the mind, that creates (through consistent practice) the channel, if you will, through which desire begins to move down and re-educate the emotional body, and even the cellular structure of the physical body, and all of the lesser avenues of thinking that occur within the intellect — so that everything involved in your being is integrated, working together, and focused on the fulfillment of that one grand desire to accept your function in this world. And your function is healing your sense of separation from God.
How then, to apply intention? Each day then, just as you have used time to teach yourself to be easily distracted, you need only apply one question, to which, you ask yourself daily:
What is it that I most desire?
What am I doing on this planet? What am I committed to?
Those latter are just other forms of the fundamental question. And as you keep practicing asking that question, the answer will become clearer and clearer. For you see, it is the question that influences, stimulates, gives birth to, the answer. For the Universe is always answering your questions. And when you ask unclear questions, you get unclear answers.
Therefore, become crystal clear with your intention and remind yourself of it daily.
My intention is to use time constructively for the relearning of what it means to abide in the Kingdom of Heaven and to fulfill my function. And my function is healing. And healing requires the presence of Christ, for only Christ can express the Love that brings healing into being.
Desire and intention — and in the field of time, these stages unfold as one matures in The Way of the Heart. Desire and intention are critical.
The third stage of the process whereby the mind is wholly corrected, and one returns home, is the stage of allowance. For the egoic world does not teach you to allow; it teaches you to strive. You must be the maker and the doer. You must find a way to manipulate or control your environment in order that it conform itself to the image you are holding in your mind. And all of that is well and good, and there are many beings who learn some valuable lessons by following the path of certain teachers that will teach you that you can create whatever you want. And that seems like such a big deal until you realize that’s what you’re doing all of the time. You are always creating exactly what you decree — and it’s no big deal and it’s not a secret.
But there will be those that will teach you,
Well, just go into your mind, ask yourself what you want, and when you see that picture of that Mercedes, then you simply do all of these little magical tricks and pretty soon you end up with a Mercedes.
The problem with that, although it can be a useful stage, is that the intellect, the worldly part of your mind, can only desire what it has been programmed to desire.
The worldly part of your mind says,
Well, I have to transport my body around in this plane. Automobiles do that. The world tells me that a Mercedes is a grand way of doing this, therefore, I will create the desire of wanting a Mercedes.
And when you manifest the Mercedes, you fool yourself into thinking that you’ve made great progress when, in fact, all you’ve done is done what you’ve always done. You have chosen what your experience will be and you have manifested it. There is nothing new about that, although, by so doing, you can begin to regain confidence in your ability to manifest.
But The Way of the Heart is about something else. Allowance, in this pathway, means that you begin to view your life differently. It is not a struggle to get out of high school and create a career by which you can create golden coins, by which you can create the proper house in the proper environment so that your ego feels “successful” and, therefore, of being “worth” Love. Be honest with yourself — is not your world built on such premises?
If only I can make my life look successful around me, then I will be accepted, then I can love myself, at least a little. Maybe I can get other people to love me.
That’s not it at all. The Way of the Heart begins with the recognition that you are already loved by the only Source that matters, that you have come for a much higher purpose that can be made manifest in the ways of the world, but is not of the world.
Allowance, then, is the cultivation of a way of looking at the events of your life, not as obstacles to getting what you want, but as stepping stones, each of which presents you with a blessing of the lessons required to heal the obstacles — not to success, but to the presence of Love as the source and ground of your being. In the stage of allowance, then, we begin to cultivate an acceptance of all things in our experience. We begin to see that because we have made a commitment to awakening and incarnating only Christ, that the Universe is already conspiring to bring the people and events into our lives, on a moment to moment basis, that can best provide us with exactly what we most need to learn or become aware of.
And so, messengers are sent. That messenger could come in the form of someone whom you fall in love with, and there is something there for you to learn. It could be that you’ve been blocking yourself from feeling Love for other people, and now someone finally comes that blasts down the door and you can’t help but feel that feeling. The messenger could be someone who comes as the grain of sand within the oyster that causes the friction within you that nudges you from your sleep, and you realize that you’ve been operating out of some very dysfunctional patterns and that you’ve got to get a better grip, shall we say, upon the Truth of who you are. It may be that you need to learn to express your feelings more. It may be that you need to accept your own creativity more. Something will bring up to you, through your messengers, that which causes you to finally be responsible and be honest about where you are.
For instance, if you think,
Well, I never get angry anymore. After all, I’m a very spiritual person. I just got out of seminary and I know it all now. So, ah yes, I’ll just live in heavenly bliss.
And events begin to happen. Perhaps a, um, hmm — we’ll use this for an example — perhaps a gay couple moves into your neighborhood and you discover that you have some very deeply seated perceptions that there is something wrong with that sexual orientation. They are messengers, sent to you by the Universe to push you to look more deeply.
Allowance, then, is the cultivation of a quality of awareness in which you rest in the recognition that your life is no longer your own to dictate and control, but that rather, you’ve given it over to the Source of your own beingness, to that depth of wisdom in the depth of the ocean that knows best how to bring about what is required to push up the dross from within your consciousness, so that you can release it.
Allowance cultivates trust. Allowance is the way in which intention and desire come to work ever more fully in the third dimension of your experience — the field of time. Allowance is a submission, but not a naive submission. Allowance changes your perception of what you see as the world around you.
You begin to realize that you don’t really live in a real world at all. You live in a field of vibrations and energies that is operated by the Law of Attraction, resonance. And you begin to be willing to allow certain things to fall out of your life, even family and friends, trusting that because of your desire and intention, what passes out of your life must be okay, for it will be replaced by new vibrational patterns which come in the form of messengers — events, places, persons and things — that can carry you on the upward spiral of awakening.
Allowance means the beginning stages of the cultivation of humility and the recognition that you must finally submit to something beyond the intellect and the control of the egoic part of the mind — that the maker and doer that’s been trying to do it all is finally recognized as being inadequate.
As these three stages mature, you rest into the final stage of surrender. And surrender means there is no longer any restlessness. Surrender means you know through every fiber of your being that there’s no one here living a life, there is Life flowing through the body-mind personality, for as long as it lasts. Here is where the mystical transformation is culminated or completed. It is here that you understand the meaning of the teaching,
I live; yet not I, but Christ dwelleth as me.
Surrender is a stage in which perfect peace is the foundation, not for passivity, not for inactivity, but even more activity.
You find yourself, as long as you are in the world, being busier and busier, asked to do more and more. You become even more responsible. And eventually, you come to see that because you are Christ, you are responsible for the whole of Creation. And you cannot think a thought without disturbing the farthest of stars. It is that responsibility from which you have shrunk and tried to contain yourself as a tiny myopic piece of foam, all because you’ve feared being responsible for the whole.
But The Way of the Heart corrects your perception, in which you come to recognize that your greatest joy, your greatest fulfillment, is in wholly and deliberately accepting responsibility for the whole of Creation. Why? Because you suddenly realize you’re not the maker and doer, that you can accept responsibility for anything and everything, because through you all power under Heaven and Earth is made to flow, to manifest the Love of God. So, in short, it’s in God’s hands, not yours. Nevertheless then,
Not my will, but Thine be done.
Does that begin to make sense to you? Do you see how it changes how you’ve even been taught to interpret my teachings?
Desire, intention, allowance, surrender — but it is a surrender into a way of being that the world can never know. It is surrender into a way of being in which you may never receive — what you call this, in your world — an Oscar for your acting. But it is a way of being in which your consciousness becomes totally open to your union with all of Creation. And you will talk with a leaf as it falls from a tree. You will see the soul of the kitten that you pet. And you will talk with angels and masters. You’ll be involved in board meetings in the high cosmic conference rooms.
And you will know that the body-mind that you once thought was yours is little more than a temporary teaching device, a tool to be picked up and utilized at God’s direction, and one to be put aside when its usefulness is done. So that even when it is time to go through the transition that you know as death, nothing will disturb your peace. And as the body dies, which means simply that your attention begins to release itself from it — just like the hand of a carpenter is released from the handle of a hammer, and the hammer simply is laid down on the table and the carpenter goes in for dinner, and forgets about it. You’ll be able to watch even the process that your world calls death, with total equanimity and joy.
You’ll watch your spirit disengage from the body. You’ll watch it crumble into lifelessness so that all of your attention becomes focused in a wholly new dimension, a dimension that is so vast that you will be able to look down upon the Earth plane, not unlike the way you might choose to hold a pebble in the palm of your hand, and in one quick glance you see everything about the pebble and nothing’s hidden.
Responsibility. I am one that has chosen to assume the responsibility for the pebble called Earth and all of life that dwells therein. You, too, will know that energy and reality of wrapping your fingers around the entirety of the solar system and becoming, shall we say, the God or the Savior of that dimension. And it begins by choosing to take responsibility for your pebble, your domain, your solar system, your personal dimension. And that, again, begins by saying,
I, and I alone, am the source of what I experience and perceive. I’m not a victim of the world I see. And everything I experience, I have called to myself, plain and simple — no excuses, no if’s, and’s, and but’s. That’s the way it is.
And gone will be your immaturity, your resistance, to simply being responsible for your experience.
The Way of the Heart, then, cultivates a maturity of desire, intention, allowance, surrender. And no single characteristic is of greater importance than this, and we’ve already mentioned it. It is called humility. Not the feigned humility that is taught in certain world religions, but a genuine humility. For humility doesn’t mean that you stand in front of a group of people, who stand and give you a standing ovation. And you go,
Oh, gosh! You don’t have to do that, you know. It’s not important.
So that you can look like you’re humble when inwardly you’re saying,
Oh God, that feels so good! Clap a little louder, clap a little longer. But I won’t tell you that.
Know you that kind of humility? Isn’t it the kind of humility you were taught in your schools? Hmm. Don’t stand there and beat upon the chest and say,
Yes! Thank you! You know, I think I’m really doing this well now.
You were not taught that that’s okay.
Genuine humility flows from the deep-seated recognition that you cannot save yourself, that you are created and not Creator, that you are effect and not cause (in an absolute sense), that something called Life is not yours, that there is something beyond your capacity of containment and intellectual understanding. And if that something ever decided to give up loving you [snaps fingers], you would cease to be, that no matter how deep you go into the depth of God, and no matter how deep you achieve an awareness and consciousness of union with God, that what God is, is forever beyond your growing capacity to understand God. It is like an Ocean of Infinite Depth. And when you realize that, strive as you might, you’ll never wrap your self, your little self, around that Source, you will rest into humility – genuine humility.
And why is this important? Because, and mark these words well, as you progress along the path of The Way of the Heart, as you dissolve and loosen the shackles upon the mind, as the interior conflicts are healed and settled, as you begin to accept the abundance that the Father would bestow upon you in all levels of life and all levels of feeling and perception, as you begin to taste of the grandeur and the greatness that would flow through you, you will discover that the “enemies” become more subtle. Every child views, at some stage, its parents as being its enemies, doesn’t it?
What do you mean I can’t have the car tonight? What do you mean I must be home by 10:00 p.m.?
The parent becomes the enemy.
But that’s a very immature and basic and naive level. As you move more and more into mastery, you will be sorely tempted to believe that you’re done. You’ll be sorely tempted to believe,
I can do this. The prayers I used to do when I began, the simple exercises of awareness I used when I started my path, I don’t need them anymore. I have mastered that.
Any time you hear a voice within yourself saying, “I’m done,” you may rest assured, you’re not. And you stand in danger of losing what you’ve gained.
Humility is the recognition that the more you move into mastery, the more there is the desire for discipline and vigilance. Discipline does not mean doing something hard that you don’t like to do. Discipline is like the skill of an artist that cultivates and refines the skill, simply out of the deep desire and delight to create more beautifully, that’s all. To discipline a muscle is done by an athlete so that the muscle works even more beautifully than it did the day before, out of the sheer delight to extend greater beauty into the world.
Therefore, the discipline of the mind that is required is to recognize that, while the body lasts and, indeed, while you remain in existence, the creations of consciousness that are unlike Love have created a whole lot of vibratory patterns that would just love to pull you down. It is the recognition that there can be a delight in consciously repeating the decision to teach only Love, and to selectively choose only the vibrational patterns in your consciousness, to be allowed into your consciousness, that reflect the Truth and the beauty and the worthiness of who you are.
Judgment can not reflect such Light. Anger and hatred can not do it. Fear and paranoia, fear of rejection, fear of the opinions of others — such vibrations can never reflect the regalness, the greatness, the grandeur of your Being. Therefore, understand well that humility is absolutely essential. For paradoxically, as greatness is expressed through you, the temptation still is to allow egoic energies to make a home in your mind. And the ego’s voice will say,
Boy, you are really quite a master, you know? You really deserve all this adulation. Why don’t you keep ten percent of it for yourself?
A master accepts the Love offered, the gratitude offered by those whom his or her teachings have touched and gives it all to God, recognizing that of themselves these things could not have been done. I learned, too, to be tempted. And when those would come to me who were sick found healing in my presence, it was very tempting to want to say,
Yes, look what I’ve done. I’ve really earned this. I spent forty days and forty nights in the desert. I’ve been to India and Tibet. I’ve been to England. I’ve studied with all of the masters of Egypt. Yes, I really deserve to be seen as a healer and a teacher.
But I learned, through humility, to remember the simplicity that, of myself, I can do nothing. I cultivated within myself the art of always being a student of Love, and not the professor of Love, who thinks he’s done just because he has a lot of letters after his name. So you see that as you progress, and as you allow more of the abundance of God’s Love to flow through you, you see you begin to stand up out of the crowd, and you begin to attract those that want the Light. And as that occurs, you must practice discipline and vigilance by remembering humility always, until you are remembering it with every breath.
And why? If you are living in this world, and feel that no one looks up to you, no one takes you as authority, there is only one reason. You have resisted the Truth of your being, and through denial have pushed God’s Light away out of your fear, your deep-seated fear, that you might appear to be different than everybody else. And the world would teach you to be a doormat so that you fit in, and don’t ruffle anybody’s feathers. But as you become empowered, one way you’ll know that it’s occurring is that some people won’t like you. You’ll push their buttons just by walking into the room, for darkness abhors Light. It’s that simple.
Humility is absolutely essential. Through the doorway of humility, the Light of Power can be turned on through you, in ever greater voltages. And if that voltage doesn’t seem to be flowing through your mind, look well to see if you are remembering humility and giving yourself to it. For the Light of God can only shine through you to the degree that you are willing to take responsibility for it, which involves giving the fruits of it back to its Source, and not claiming it as your own. And when you claim nothing for yourself, all things can flow through you. And the Holy Spirit can gather millions of beings to come to you in many planes, because it knows you will not distort the Love of God by usurping God’s position and putting yourself upon the throne.
Humility is a chief characteristic to cultivate. Therefore, when you pray, indeed ask for greatness. Let the Father know that you are ready for the fullness of Christ to be incarnate and simply hold the promise within that you will always remember that you are not the doer and the maker. You are merely the one who has come to recognize that only the Love of God can fulfill you as a soul. Only the fulfillment of your purpose to be a channel for Love can bring you the success that you truly seek. When you are fully committed to that, rather than being committed to wondering about other people’s opinions, then that Power can begin to move through you.
When you are willing to let go of the world, Heaven will come to replace it. When you’re willing to let go of your need for egoic grandness, true grandeur will begin to pour forth through you. There is a paradox within Spirit. Learn to discern it. Become a master of it. And never neglect the need for discipline based on the foundation of humility. You see, this is what has caused you to fear the energy of desire, because in the past (and that can go back a long way), you have decided to find out what it would be like to let all of that power be claimed as your own — to be used to serve the voice of ego. And that is what you are afraid of. But if you cultivate these stages and found them in humility, you will never need to fear the misuse of desire.
Therefore, in your prayers, as often as you can remember to do so, remember that what you decree, is. So speak clearly within yourself.
Source, Creator, God, Goddess, All That Is, Abba, I am ready to be what You created me to be. I choose to remember that I am effect and not cause. Thy Will be done, knowing that Your Will is my full happiness. Reveal then, that path through which that happiness can be known. For my way has never worked, but Your way always does.
Then, in each day remember the energy of appreciation. It is well and good to appreciate one another. But in the privacy of your own meditation and prayer, appreciate how the power of that Source of Love I’ve called Abba or God, is living and moving and breathing to bring the people, the books, the teachers, the experiences that are gently unraveling the cocoon of ego around you, awakening you to the Truth, and the beauty, and the majesty, and the grandeur, and the greatness that Life, Itself, is — that wants to breathe through you as magically and powerfully as it breathes through a thunder storm, or the leaf on a tree, or the radiance in a newborn baby’s eyes.
That Life is what you are. That Life is the presence of God’s Love, the Depth of the Ocean welling up into the Waves of Creation. Let, therefore, that Life alone be your guide in all things, and rest in appreciation before the Infinite Mystery that Life is, and say yes to it. Say yes to Life — that you are willing to let the fullness of it wash through you and carry you into an ever deepening understanding and comprehension of all that God is. And, indeed, if you would well receive it, resting in the awareness of divine humility is the sweetest of experiences that you can ever know.
Many of you look upon me going,
Oh! Where Jeshua abides, would I ever love to be there. Think a thought and you’re with someone. Think a thought and you’re in that universe. You never have to blink an eye because you don’t have one.
I tell you this, where I abide is in a vibrational frequency with many, many other beings whose consciousness never wavers for an instant from the deep appreciation and humility before the Mystery of All that God Is — the great delight of knowing that we live, yet not us but our Creator lives as us. The only difference between being a master and being a student is that the master has mastered the art of always being a student. Think about that one.
Desire, intention, allowance, surrender — what do you truly want? Are you willing to feel it and let that thread of desire carry you home? Can you remember to use time constructively, by focusing your intention, by reminding yourself of what you’re truly here for? You’re not here to survive, you’re here to live as the Truth of who you are.
Allowance — not a passive acceptance of things as they are, but a recognition that there is something quite beautiful at work. There is an Intelligence, a Love that knows you better than yourself and is presenting you, moment to moment, with jewels and gems and lessons and blessings, that something is weaving the tapestry of your life, and nothing is happening by accident.
Surrender — the cultivation of the recognition that your happiness can be found only in the submission of your will to the Will of God. For your will has been to be in conflict and struggle and limitation. The Father’s Will is that you live without conflict, in peace, and joy, and fulfillment, and happiness. ‘Tis called bliss.
Humility — if ever you wonder how to anchor your awareness in humility, stop what you’re doing and ask yourself this question:
Did I create myself?
You will know darn well that the answer is:
No, I don’t even know when I was created. Something birthed me. What is it?
That will bring you to humility rather quickly. Do you know how to give birth to a star? No! Do you know how to give birth to a leaf on a tree? No! Do you even know how you lift your hand from your lap? No! What then, do you know? Nothing! Allow yourself to understand that you don’t know anything. And in that state of divine ignorance, you will rest in a humility that finally allows your Creator to move through you and reveal to you all things.
So, beloved friends, The Way of the Heart is that way which corrects perception and brings right-mindedness, so that you are no longer the maker and the doer and the director. Your opinions will come to mean nothing to you whatsoever. And out of a grand emptiness, you will discover a perfect peace. And Life will bear you on Its wings. And through you, Life will express, in ever greater dimensionality, the exquisite and infinite Love and Power and Creativity that is God, until you swear that God is all there is. And there will be no place to find a trace of you. For if enlightenment is the ending of separation, how can there be a maker and doer? Can the wave direct itself? The ego is the attempt to do so, and it always fails.
Peace then, be with you always. Let peace pervade your being at all times. And know that you are safe in the Love of God that arises from that great Source of Mystery, and would move through you with every breath you breathe and every word you speak, until you hear only that impetus of guidance that wells up from the depth of your being as a Gentle Voice that you trust completely. And you will know the freedom that you seek.
And with that, we, indeed, would leave you now. Yet we go nowhere, for you already abide where we are. Trust this. Know this. Rely on this. And explore The Way of the Heart. And by such exploration, you will come to know the Truth of Love.
Be you, therefore, at peace, beloved friends.
Amen.`

export default text;